import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    width: "100%",
  },

  titulo: {
    fontSize: 28,
    fontWeight: "bold",
  },
  input: {
    color: "white",
    backgroundColor: "gray",
    padding: 1,
    height: 20,
    width: 300,
    marginTop: 15,
  },
  inputcontainer: {
    height: 180,
    marginBottom: "15%",
    marginTop: "5%",
    borderRadius: 10,
    backgroundColor: "white",
    padding: 15,
    height: 380,
    borderRadius: 12,
  },
  inputcontainerlog: {
    height: 350,
    width: 350,
    marginBottom: "5%",
    marginTop: "5%",
    borderRadius: 10,
    backgroundColor: "white",
    padding: 40,
    borderRadius: 12,
  },
  form: {
    flex: 1,
    backgroundColor: "#ffffff",
    padding: 20,
    borderRadius: 10,
    margin: 15,
    alignItems: "center",
    justifyContent: "center",
  },
  botaoLog: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5792EB",
    pisition: "absoulute",
    fontSize: 30,
    borderRadius: 15,
    padding: 5,
    marginTop: 10,
    width: "60%",
    height: "5%",
  },
  botaoCad: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5792EB",
    position: "absoulute",
    fontSize: 30,
    borderRadius: 15,
    padding: 5,
    width: "60%",
    height: "5%",
  },
  botaoOp: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "white",
    borderColor: "#007BFF",
    borderWidth: 2,
    borderRadius: 15,
    position: "absoulute",
    fontSize: 30,
    borderRadius: 15,
    padding: 5,
    marginTop: 10,
    width: "60%",
    height: "5%",
  },
  botaoList: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#5792EB",
    position: "absoulute",
    fontSize: 30,
    borderRadius: 15,
    padding: 5,
    marginTop: 60,
    width: "60%",
    height: "5%",
  },

  imagem: {
    height: 200,
  },
  logo: {
    justifyContent: "space-evenly",
    alignItems: "flex-start",
  },
  inputPicker: {
    backgroundColor: "gray",
    color: "white",
    marginTop: 20,
    paddingLeft: 8,
    marginBottom: 20,
    borderRadius: 2,
  },
  textPicker: {
    color: "white",
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between", // espaça as colunas
    alignItems: "center",
    width: "100%", //pra dxa alinnhado c o titulo
    alignSelf: "center",
    marginVertical: 4,
  },

  card: {
    width: "92%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    marginVertical: 8,
  },

  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#222",
    marginBottom: 8,
    alignSelf: "flex-start",
    marginLeft: 8,
  },

  column: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "gray",
    marginHorizontal: 3,
    borderRadius: 4,
    paddingVertical: 6,
    marginTop: 10,
  },
  inputPicker: {
    marginBottom: 20,
    backgroundColor: "#fff",
    paddingLeft: 8,
  },
  inputPickerdata: {
    marginBottom: 20,
    backgroundColor: "gray",
  },
  inputPickersala: {
    marginBottom: 10,
    backgroundColor: "gray",
    padding: 6,
    marginTop: 20,
  },
  inputView: {
    width: "55%",
    marginBottom: 20,
  },

  tabelatext: {
    flex: 1,
    backgroundColor: "white",
    borderRadius: 15,
    justifyContent: "center",
    textAlign: "center",
    fontWeight: "bold",
    fontSize: 15,
    color: "black",
    marginLeft: 40,
    marginRight: 40,
    marginTop: 10,
    padding: 10,
    borderColor: "gray",
    borderWidth: 3,
  },
  tableHeader: {
    flexDirection: "row",
    backgroundColor: "#f2f4f7",
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    width: "100%",
    justifyContent: "space-between",
    marginTop: 6,
  },
  tableRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  cell: {
    flex: 1,
    paddingHorizontal: 6,
  },
  headerText: {
    fontWeight: "700",
    color: "#333",
  },
  checkboxCell: {
    width: 70,
    alignItems: "center",
  },
  header: {
    width: "100%",
    paddingTop: 18,
    paddingBottom: 12,
    paddingHorizontal: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "transparent",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#fff",
    marginLeft: 6,
  },
  drawerTab: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: [{ translateY: -20 }],
    backgroundColor: "rgba(59, 130, 246, 0.9)",
    paddingVertical: 8,
    paddingHorizontal: 6,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    elevation: 4,
  },
  drawerTabText: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "600",
  },
  primaryButton: {
    backgroundColor: "#3B82F6",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  secondButton: {
    backgroundColor: "#ffffffff",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 10,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#fff",
    fontWeight: "700",
  },
  secondButtonText: {
    color: "#066ce0ff",
    fontWeight: "700",
  },
  formCard: {
    width: "92%",
    backgroundColor: "rgba(255,255,255,0.92)",
    borderRadius: 12,
    padding: 30,
    marginVertical: 12,
    elevation: 2,
  },
  inputOutlined: {
    backgroundColor: "#fff",
    fontSize: 14,
    marginBottom: 10,
  },
  selectWrapper: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    overflow: "hidden",
    marginBottom: 10,
    backgroundColor: "#fff",
  },
  formActions: {
    width: "100%",
    alignItems: "center",
    marginTop: 8,
  },
  drawerHeader: {
    padding: 16,
    backgroundColor: "#3B82F6",
    flexDirection: "row",
    alignItems: "center",
  },
  drawerEmail: {
    color: "#e6f0ff",
    fontSize: 12,
  },
  menuGrid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    paddingVertical: 16,
    gap: 12,
  },
  menuCard: {
    width: "48%",
    backgroundColor: "rgba(255,255,255,0.88)",
    borderRadius: 12,
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
    elevation: 3,
    minHeight: 110,
  },
  menuCardIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  menuCardText: {
    fontWeight: "600",
    color: "#1f2937",
    fontSize: 12,
    textAlign: "center",
  },
  listCard: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 10,
    paddingLeft: 70,
    paddingRight: 70,
    paddingBottom: 12,
    paddingTop: 12,
    marginVertical: 6,
    elevation: 2,
    borderLeftWidth: 4,
    borderLeftColor: "#3B82F6",
  },
  listCardText: {
    fontWeight: "600",
    color: "#1f2937",
    fontSize: 14,
    marginRight: 10,
  },
  listCardSubtext: {
    fontSize: 12,
    color: "#6b7280",
    marginTop: 4,
    marginRight: 10,
  },
  listContainer: {
    flex: 1,
    alignItems: "center",
    paddingBottom: 20,
  },
  filterCard: {
    width: "92%",
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 12,
    elevation: 2,
  },
  tabela: {
    justifyContent: "center",
    alignItems: "center",
    marginLeft: "22",
    marginRight: "22",
  },
  touch: {
    backgroundColor: "gray",
  },
  date: {},
});
